import turtle

# Прямоугольник
turtle.reset()
turtle.forward(100)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(50)

turtle.up()
turtle.forward(300)
turtle.down()

# Шестиугольник (правильный)
turtle.right(90)
turtle.forward(50)
turtle.right(60)
turtle.forward(50)
turtle.right(60)
turtle.forward(50)
turtle.right(60)
turtle.forward(50)
turtle.right(60)
turtle.forward(50)
turtle.right(60)
turtle.forward(50)

turtle.up()
turtle.right(90)
turtle.forward(200)
turtle.down()

# Треугольник (равносторонний)
turtle.left(30)
turtle.forward(50)
turtle.left(90)
turtle.left(30)
turtle.forward(50)
turtle.left(120)
turtle.forward(50)

# Звезда
turtle.up()
turtle.left(30)
turtle.forward(300)
turtle.down()
turtle.width(10)
turtle.left(18)

turtle.forward(70)
turtle.up()
turtle.forward(45)
turtle.down()
turtle.forward(70)
turtle.right(144)

turtle.forward(70)
turtle.up()
turtle.forward(45)
turtle.down()
turtle.forward(70)
turtle.right(144)

turtle.forward(70)
turtle.up()
turtle.forward(45)
turtle.down()
turtle.forward(70)
turtle.right(144)

turtle.forward(70)
turtle.up()
turtle.forward(45)
turtle.down()
turtle.forward(70)
turtle.right(144)

turtle.forward(70)
turtle.up()
turtle.forward(45)
turtle.down()
turtle.forward(70)
turtle.right(144)
